apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: delivery-service
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: delivery-service
    spec:
      containers:
        - name: delivery-service
          image: gcr.io/alien-airfoil-290817/delivery-service
          env:
          - name: mysql
            value: 10.8.14.22
          ports:
            - containerPort: 9111
---
apiVersion: v1
kind: Service
metadata:
  name: delivery-service
  labels:
    name: delivery-service
spec:
  ports:
    - port: 8082
      targetPort: 9111
	  protocol: TCP
  selector:
	app: delivery-service
  type: LoadBalancer