apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ordering-service
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: ordering-service
    spec:
      containers:
        - name: ordering-service
          image: gcr.io/alien-airfoil-290817/ordering-service-v1
          env:
          - name: mysql
            value: 10.8.14.22
          ports:
            - containerPort: 9112
---
apiVersion: v1
kind: Service
metadata:
  name: ordering-service
  labels:
    name: ordering-service
spec:
  ports:
    - port: 8081
      targetPort: 9112
      protocol: TCP
  selector:
    app: ordering-service
  type: LoadBalancer