apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: restaurant-service
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: restaurant-service
    spec:
      containers:
        - name: restaurant-service
          image: gcr.io/alien-airfoil-290817/restaurant-service
          env:
          - name: mysql
            value: 10.8.14.22
          ports:
            - containerPort: 9113
---
apiVersion: v1
kind: Service
metadata:
  name: restaurant-service
  labels:
    name: restaurant-service
spec:
  ports:
    - port: 8080
      targetPort: 9113
      protocol: TCP
  selector:
    app: restaurant-service
  type: LoadBalancer